# Generated by Django 5.0.3 on 2024-05-04 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_sensor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.measurement')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.sensor')),
            ],
        ),
        migrations.DeleteModel(
            name='MesurmentSensor',
        ),
    ]
